### ISSUE TITLE
Commit 3a2a6539554007342e8fdc87edefb938f3f7b6c9 didn't display the existing notes.

### ISSUE THREAD

**Issue by cjfaeldonea** [jvc1019/CMSC128#24]
![image](https://user-images.githubusercontent.com/72564347/98312579-ffe7a680-200c-11eb-8cd0-ed9f48cf26e6.png)

**Comment by cjfaeldonea** [comment]
![image](https://user-images.githubusercontent.com/72564347/98312846-80a6a280-200d-11eb-88dd-f40a8b82a9c4.png)

**Comment by emancarp** [comment]
add notes backend is currently being worked on pa

**Comment by RobJinon** [comment]
na resolve na po
